<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-DB5NH1R" name="com.sample.example.TestNGGroups" tests="11" failures="1" timestamp="06 Sep 2021 05:58:03 GMT" time="0.106" errors="0">
  <testcase name="tc4" time="0.004" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc3" time="0.007" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc0" time="0.040" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc8" time="0.004" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc10" time="0.011" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc9" time="0.008" classname="com.sample.example.TestNGGroups">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.sample.example.TestNGGroups.tc9(TestNGGroups.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc9 -->
  <testcase name="tc1" time="0.000" classname="com.sample.example.TestNGGroups">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc7" time="0.016" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc6" time="0.004" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc5" time="0.004" classname="com.sample.example.TestNGGroups"/>
  <testcase name="tc2" time="0.008" classname="com.sample.example.TestNGGroups"/>
</testsuite> <!-- com.sample.example.TestNGGroups -->
